import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * La barre latérale suit l'arborescence de `docs/`.
 * Les pages du parcours guidé sont générées depuis `content/fr` par
 * `tools/build-content` : elles vivent dans `docs/tour/` mais leur source de
 * vérité est `content/fr/tour/`.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;